version: '3.3'
volumes:
  mongodata:
services:
  mongo:
    container_name: "mongo"
    image: mongo:3.4
    volumes:
      - mongodata:/data/db
    expose:
      - 27017

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    links:
      - mongo
