version: '2'
services:
  mongo:
    container_name: "mongo"
    image: "mongo"
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
